---
output: pdf_document
---
# AGREED TERMS

## 1. INTERPRETATION

The following definitions and rules of interpretation apply in this agreement. 

## 1.1. Definitions: 

Business Day: a day other than a Saturday, Sunday or public holiday in England 

when banks in London are open for business. 

Future Works: the works described in Schedule 2. 

VAT: value added tax or any equivalent tax chargeable in the UK or elsewhere. 

Works: the works described in Schedule 1. 

1.2. Clause, Schedule and paragraph headings shall not affect the interpretation of this 

agreement. 

1.3. A person includes a natural person, corporate or unincorporated body (whether or not 

having separate legal personality). 

1.4. The Schedules form part of this agreement and shall have effect as if set out in full in 

the body of this agreement. Any reference to this agreement includes the Schedules. 

1.5. References to clauses and Schedules are to the clauses and Schedules of this 

agreement. 

1.6. Unless the context otherwise requires, words in the singular shall include the plural 

and in the plural shall include the singular.

